apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agents
spec:
  serviceAccountName: jenkins-admin # This is the Serviceaccount of the Jenkins Master , defined in jenkins-service-acount.yaml 
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-4
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  - name: docker
    image: docker:20.10-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}
